### ISSUE TITLE
運用方法がよくわからないのはいろいろ問題

### ISSUE THREAD

**Issue by nsym2nd** [nsym7372/sample1#4]
masterブランチへのpush禁止とか

**Comment by nsym2nd** [comment]
- [X] Write the code
- [ ] Write all the tests
- [ ] Document the code

**Comment by nsym2nd** [comment]
```java
for(int i=0 ; i < 5 ; i++)
{
   System.out.println("i is : " + i);
}
```

**Comment by nsym7372** [comment]
> masterブランチへのpush禁止とか

返信

**Comment by nsym7372** [comment]
![karou_man](https://user-images.githubusercontent.com/25893196/31266072-03f40fee-aaad-11e7-936d-85b048b84d48.png)
